---
  title: "MILSON"
  groups: 
    - 
      pathname: "about"
      documents: 
        - 
          filename: "purpose.md"
          title: "Purpose"
          id: "purpose"
        - 
          filename: "google-group.jade"
          title: "Google Group"
          id: "google-group"
      title: "About"
      id: "about"
    - 
      pathname: "data-types"
      documents: 
        - 
          filename: "glossary.md"
          title: "Glossary"
          id: "glossary"
        - 
          filename: "geolocation.md"
          title: "geolocation"
          id: "geolocation"
        - 
          filename: "orientation.md"
          title: "orientation"
          id: "orientation"
        - 
          filename: "observation.md"
          title: "observation"
          id: "observation"
      title: "Data Types"
      id: "data-types"
    - 
      pathname: "transmission"
      private: true
      documents: 
        - 
          filename: "transmission.md"
          title: "transmission"
          id: "transmission"
      title: "Transmission"
      id: "transmission"
    - 
      pathname: "versioning"
      documents: 
        - 
          filename: "semver.md"
          title: "SemVer"
          id: "semver"
      title: "Versioning"
      id: "versioning"
  languages: 
    - "xml"
    - "bash"
    - "javascript"
    - "java"
    - "cs"
    - "cpp"
  templates: 

